### ISSUE TITLE
Use Parser inside main

### ISSUE THREAD

**Issue by prastoin** [AdonisEnProvence/Turing#20]
# TODO
- [ ] Call global parser function, on error call `format_error` with given error and exit the program +  Integ Tests.
- [ ] Verify given filename exists, if not log an error and exit the programe +  Integ Tests.
- [ ] If not enough args are given or too much display the program usage + Integ tests.
